#!/usr/bin/env python3
"""
Script para generar configuración de reCAPTCHA para localhost
"""

print("=" * 60)
print("CONFIGURACIÓN DE reCAPTCHA PARA LOCALHOST")
print("=" * 60)
print()
print("Para eliminar el mensaje 'This reCAPTCHA is for testing purposes only':")
print()
print("1. Ve a: https://www.google.com/recaptcha/admin")
print("2. Haz clic en '+ Crear'")
print("3. Configura:")
print("   - Etiqueta: 'UCS Sistema Local'")
print("   - Tipo: 'reCAPTCHA v2'")
print("   - Dominios: 'localhost, 127.0.0.1'")
print("4. Acepta los términos y crea el sitio")
print("5. Copia las claves generadas")
print()
print("6. Actualiza sistema/settings.py con:")
print("   RECAPTCHA_PUBLIC_KEY = 'TU_CLAVE_PUBLICA'")
print("   RECAPTCHA_PRIVATE_KEY = 'TU_CLAVE_PRIVADA'")
print()
print("7. Reinicia el servidor Django")
print()
print("=" * 60)
print("CLAVES ACTUALES (CON MENSAJE DE PRUEBA):")
print("=" * 60)
print("Pública:  6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI")
print("Privada:  6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe")
print()
print("Estas claves funcionan pero muestran el mensaje rojo.")
print("Para eliminarlo, usa claves reales registradas para localhost.")
print("=" * 60)
