# Generated by Django 5.0.4 on 2024-04-24 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pnf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trayecto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('palabras_clave', models.TextField()),
                ('autores', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_subido', models.DateTimeField()),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsistem.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsistem.trayecto')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsistem.tutor')),
            ],
        ),
    ]
