# Generated by Django 5.0.4 on 2024-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/proyectos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_subido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
