# Generated by Django 5.0.4 on 2024-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0002_proyecto_archivo_alter_proyecto_fecha_subido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tutor',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_subido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
