# Generated by Django 5.0.6 on 2024-05-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0003_alter_proyecto_tutor_alter_proyecto_fecha_subido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/proyectos/'),
        ),
    ]
