# Generated by Django 5.0.6 on 2024-05-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0004_alter_proyecto_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_estudiante', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='municipio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_comunidad',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='parroquia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tutor_metodologico',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appsistem.seccion'),
        ),
    ]
