# Generated by Django 5.0.6 on 2024-05-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0005_seccion_proyecto_estado_proyecto_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='seccion_estudiante',
            field=models.TextField(null=True),
        ),
    ]
