# Generated by Django 5.0.6 on 2024-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0006_alter_seccion_seccion_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='seccion_estudiante',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
