# Generated by Django 5.0.6 on 2024-06-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0008_proyecto_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
