# Generated by Django 5.0.6 on 2024-06-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0009_proyecto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='status',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='revisado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
