# Generated by Django 5.2.6 on 2025-09-30 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0010_remove_proyecto_status_proyecto_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('EN_REVISION', 'En Revisión'), ('CORREGIDO', 'Corregido'), ('APROBADO', 'Aprobado')], default='EN_REVISION', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
