# Generated by Django 5.2.6 on 2025-10-01 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MOMENTO I', 'MOMENTO I'), ('MOMENTO II', 'MOMENTO II'), ('MOMENTO III', 'MOMENTO III'), ('MOMENTO IV', 'MOMENTO IV')], max_length=20)),
                ('estado_revision', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='appsistem.proyecto')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MomentoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='momentos/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('etiqueta', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='appsistem.momento')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
