# Generated by Django 5.2.6 on 2025-10-01 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0013_remove_proyecto_feedback_alter_proyecto_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='momentoversion',
            name='origen',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=12),
        ),
        migrations.AddField(
            model_name='momentoversion',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_subidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
