# Generated by Django 5.2.6 on 2025-10-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momento',
            name='estado_revision',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CORREGIDO', 'Corregido'), ('CON_CORRECCIONES', 'Con correcciones')], default='PENDIENTE', max_length=20),
        ),
    ]
