# Generated by Django 5.2.6 on 2025-10-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0017_profile_failed_login_attempts_profile_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
