# Generated by Django 5.2.6 on 2025-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0018_profile_is_trashed_profile_trashed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=12),
        ),
    ]
