# Generated by Django 5.2.6 on 2025-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0019_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=12),
        ),
    ]
