# Generated by Django 5.2.6 on 2025-10-14 21:46

import appsistem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0020_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentoversion',
            name='archivo',
            field=models.FileField(upload_to='momentos/', validators=[appsistem.models.validate_document_file_model]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/', validators=[appsistem.models.validate_document_file_model]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20, null=True),
        ),
    ]
