# Generated by Django 5.2.6 on 2025-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0021_alter_momentoversion_archivo_alter_proyecto_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
