# Generated by Django 5.2.6 on 2025-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0022_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado_proyecto',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
