# Generated by Django 5.2.6 on 2025-10-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0023_proyecto_estado_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
    ]
