# Generated by Django 5.2.6 on 2025-10-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsistem', '0027_alter_proyecto_estado_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado_proyecto',
        ),
    ]
