# Generated by Django 3.2.25 on 2025-10-15 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsistem', '0028_remove_proyecto_estado_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='is_trashed',
            field=models.BooleanField(default=False, verbose_name='En Papelera'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Papelera'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_enviados_papelera', to=settings.AUTH_USER_MODEL, verbose_name='Enviado a Papelera por'),
        ),
    ]
